# Generated by Django 5.2.3 on 2025-07-05 00:59

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='案件名称')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='案件编号')),
                ('filing_unit', models.CharField(choices=[('direct', '直属单位'), ('tianyuan', '天元分局'), ('lusong', '芦淞分局'), ('hetang', '荷塘分局'), ('shifeng', '石峰分局'), ('dongjiaba', '董家塅分局'), ('economic', '经开区分局'), ('lukou', '渌口分局'), ('liling', '醴陵市公安局'), ('youxian', '攸县公安局'), ('chaling', '茶陵县公安局'), ('yanling', '炎陵县公安局')], max_length=20, verbose_name='立案单位')),
                ('case_summary', models.TextField(verbose_name='简要案情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.case_attachment_upload_path, verbose_name='附件文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_attachments', to='projects.project', verbose_name='所属案件')),
            ],
            options={
                'verbose_name': '案件附件',
                'verbose_name_plural': '案件附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', '只读'), ('edit', '编辑'), ('admin', '管理员')], default='read', max_length=10, verbose_name='权限')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='案件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '案件参与人员',
                'verbose_name_plural': '案件参与人员',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectMember', to=settings.AUTH_USER_MODEL, verbose_name='参与人员'),
        ),
    ]
