# Generated by Django 5.2.3 on 2025-07-02 03:49

import mindmaps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('content', models.TextField(verbose_name='节点内容')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('hyperlink', models.URLField(blank=True, null=True, verbose_name='超链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '思维导图节点',
                'verbose_name_plural': '思维导图节点',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mindmaps.models.node_attachment_upload_path, verbose_name='附件文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '节点附件',
                'verbose_name_plural': '节点附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='旧数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='新数据')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '节点编辑日志',
                'verbose_name_plural': '节点编辑日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
