# Generated by Django 5.2.3 on 2025-07-05 00:59

import django.db.models.deletion
import mindmaps.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='前端生成', max_length=100, unique=True, verbose_name='节点UID')),
                ('parent_node_uid', models.CharField(blank=True, max_length=100, verbose_name='父节点UID')),
                ('is_root', models.BooleanField(default=False, verbose_name='是否为根节点')),
                ('is_system_default', models.BooleanField(default=False, help_text='系统默认生成的节点，不能删除和修改内容，只能添加子节点', verbose_name='系统默认节点')),
                ('text', models.TextField(verbose_name='节点文本')),
                ('rich_text', models.BooleanField(default=False, verbose_name='是否富文本')),
                ('expand', models.BooleanField(default=True, verbose_name='是否展开')),
                ('icon', models.JSONField(blank=True, default=list, verbose_name='图标列表')),
                ('hyperlink', models.URLField(blank=True, verbose_name='超链接地址')),
                ('hyperlink_title', models.CharField(blank=True, max_length=255, verbose_name='超链接标题')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签列表')),
                ('generalizations', models.JSONField(blank=True, default=list, verbose_name='概要数据')),
                ('associative_line_targets', models.JSONField(blank=True, default=list, verbose_name='关联线目标节点')),
                ('associative_line_text', models.JSONField(blank=True, default=dict, verbose_name='关联线文本数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='节点层级')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序顺序')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nodes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.project', verbose_name='所属案件')),
            ],
            options={
                'verbose_name': '思维导图节点',
                'verbose_name_plural': '思维导图节点',
                'ordering': ['level', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociativeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='关联线文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associative_lines', to='projects.project', verbose_name='所属项目')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_lines', to='mindmaps.mindmapnode', verbose_name='源节点')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_lines', to='mindmaps.mindmapnode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '节点关联线',
                'verbose_name_plural': '节点关联线',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mindmaps.models.node_attachment_upload_path, verbose_name='附件文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_attachment', to='mindmaps.mindmapnode', verbose_name='所属节点')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_node_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '节点附件',
                'verbose_name_plural': '节点附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='旧数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='新数据')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='mindmaps.mindmapnode', verbose_name='节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '节点编辑日志',
                'verbose_name_plural': '节点编辑日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NodeGeneralization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='概要文本')),
                ('rich_text', models.BooleanField(default=False, verbose_name='是否富文本')),
                ('style_data', models.JSONField(blank=True, default=dict, verbose_name='概要样式')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalization_objects', to='mindmaps.mindmapnode', verbose_name='所属节点')),
            ],
            options={
                'verbose_name': '节点概要',
                'verbose_name_plural': '节点概要',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='支持 jpg, jpeg, png, gif, webp 格式', upload_to=mindmaps.models.node_image_upload_path, verbose_name='图片文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('width', models.PositiveIntegerField(verbose_name='图片宽度')),
                ('height', models.PositiveIntegerField(verbose_name='图片高度')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='图片标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_image', to='mindmaps.mindmapnode', verbose_name='所属节点')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_node_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '节点图片',
                'verbose_name_plural': '节点图片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='标签文本')),
                ('style_data', models.JSONField(blank=True, default=dict, verbose_name='标签样式')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_objects', to='mindmaps.mindmapnode', verbose_name='所属节点')),
            ],
            options={
                'verbose_name': '节点标签',
                'verbose_name_plural': '节点标签',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mindmapnode',
            index=models.Index(fields=['project', 'parent_node_uid'], name='mindmaps_mi_project_b95535_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapnode',
            index=models.Index(fields=['node_id'], name='mindmaps_mi_node_id_b292ca_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapnode',
            index=models.Index(fields=['creator'], name='mindmaps_mi_creator_fc9e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='mindmapnode',
            index=models.Index(fields=['level', 'sort_order'], name='mindmaps_mi_level_7b1753_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mindmapnode',
            unique_together={('project', 'node_id')},
        ),
        migrations.AddIndex(
            model_name='associativeline',
            index=models.Index(fields=['project', 'source_node'], name='mindmaps_as_project_e94822_idx'),
        ),
        migrations.AddIndex(
            model_name='associativeline',
            index=models.Index(fields=['project', 'target_node'], name='mindmaps_as_project_9d3e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='associativeline',
            index=models.Index(fields=['creator', '-created_at'], name='mindmaps_as_creator_0f7ac6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='associativeline',
            unique_together={('source_node', 'target_node')},
        ),
        migrations.AddIndex(
            model_name='nodeeditlog',
            index=models.Index(fields=['node', '-timestamp'], name='mindmaps_no_node_id_c7573a_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeeditlog',
            index=models.Index(fields=['user', '-timestamp'], name='mindmaps_no_user_id_289003_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeeditlog',
            index=models.Index(fields=['action', '-timestamp'], name='mindmaps_no_action_e449f6_idx'),
        ),
        migrations.AddIndex(
            model_name='nodegeneralization',
            index=models.Index(fields=['node', 'sort_order'], name='mindmaps_no_node_id_a42e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='nodetag',
            index=models.Index(fields=['node', 'sort_order'], name='mindmaps_no_node_id_d9274b_idx'),
        ),
    ]
