# Generated by Django 5.2.3 on 2025-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('text', models.TextField(verbose_name='节点文本')),
                ('image', models.URLField(blank=True, null=True, verbose_name='节点图片')),
                ('hyperlink', models.URLField(blank=True, null=True, verbose_name='超链接')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='背景色')),
                ('font_color', models.CharField(default='#000000', max_length=7, verbose_name='字体颜色')),
                ('font_size', models.IntegerField(default=14, verbose_name='字体大小')),
                ('font_weight', models.CharField(default='normal', max_length=10, verbose_name='字体粗细')),
                ('position_x', models.FloatField(default=0, verbose_name='X坐标')),
                ('position_y', models.FloatField(default=0, verbose_name='Y坐标')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '思维导图节点',
                'verbose_name_plural': '思维导图节点',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='旧数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='新数据')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '节点编辑日志',
                'verbose_name_plural': '节点编辑日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
