# Generated by Django 5.2.3 on 2025-07-01 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mindmaps', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmapnode',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nodes', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='mindmapnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mindmaps.mindmapnode', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='mindmapnode',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='nodeeditlog',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='mindmaps.mindmapnode', verbose_name='节点'),
        ),
        migrations.AddField(
            model_name='nodeeditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AlterUniqueTogether(
            name='mindmapnode',
            unique_together={('project', 'node_id')},
        ),
    ]
