# Generated by Django 5.2.3 on 2025-07-03 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0002_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmapnode',
            name='is_root',
            field=models.BooleanField(default=False, verbose_name='是否为根节点'),
        ),
        migrations.AddField(
            model_name='mindmapnode',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='系统默认生成的节点，不能删除和修改内容，只能添加子节点', verbose_name='系统默认节点'),
        ),
        migrations.AddConstraint(
            model_name='mindmapnode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('project',), name='unique_root_per_project'),
        ),
    ]
