# Generated by Django 5.2.3 on 2025-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encodings',
            field=models.TextField(blank=True, help_text='存储人脸特征编码数据，JSON格式，支持多个128维特征向量'),
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
