# Generated by Django 5.2.3 on 2025-07-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_face_encodings_delete_faceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='审核拒绝时的原因说明', verbose_name='拒绝原因'),
        ),
    ]
